### ISSUE TITLE
immunization module does not work with cross communitiy between sanela and emedo?

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/Impfmodul-Phase-I#42]
1. the former immunisations from meine-impfungen.ch were saved and published by emedo on in June2024 in the repository of emedo and were visible in the sanela patient portal as a pdf and a json document containing all the administred immunizations
2. in the activaded immunization module within sanela the immunizations were displayed from emedo (needs a cross community call to retrieve the document)
3. during the migration end of november the immunization administration document in the portal and the immunizations in the immunization module were not displayed (because the emedo community was not reachable and cross community could not work)
4. after the migration the two documents (pdf and json) are shown back up again as of today (indicated as new document) but the immunizations don't show up in the immunization module

Could it be that immunization module does not work cross community with the new plattform of emedo?

I downloaded the immunization document and reuploaded the document into the sanela (then there will be no cross-community) and the immunizations are showing up again in the module. It looks like either cross-communtiy does not work or the immunization module configuration in sanela needs to be adapted.

**Comment by qligier** [comment]
Is it because the Post system exposes two different endpoints for ITI-18 and ITI-38 transactions, which may not be the case for other implementations?

ITI-38 is not listed as an interface to the EPR:
https://github.com/ehealthsuisse/Impfmodul-Phase-I/blob/3628a45ecf5394d974020d61a3d1417feb6fdb53/Documentation/EN/04_Interfaces.md?plain=1#L18-L25

**Comment by oliveregger** [comment]
> Is it because the Post system exposes two different endpoints for ITI-18 and ITI-38 transactions, which may not be the case for other implementations?
> 
> ITI-38 is not listed as an interface to the EPR:
> 
> https://github.com/ehealthsuisse/Impfmodul-Phase-I/blob/3628a45ecf5394d974020d61a3d1417feb6fdb53/Documentation/EN/04_Interfaces.md?plain=1#L18-L25

the immunization module was working with crosscommunity between the two posts systems (sanela (post) -> emedo (post)), therefore I don't think that should be a problem

**Comment by kaisercarole** [comment]
The release [Hotfix 1.6.3](https://github.com/ehealthsuisse/Impfmodul-Phase-I/blob/main/Implementation/Releases/release-notes.md#september-2024---hotfix-163) should solve the problem.

It was not possible to read data from the abilis / bint environment without the codeSystemName. That's why in the Release 1.6.3 the XUA request field 'purpose of use' has been extended to set the codeSystemName to "EprPurposeOfUse".
Since this version was not installed it's not verified that this solves the issue. But the exchange with Abilis has narrowed the problem down to this issue.

Without this addition, it is not possible for communities to read data in the vaccination module that is stored at a community such as abilis and emedo.

**Comment by kaisercarole** [comment]
issue is resolved. 1.6.3 is installed
